server:
  port: 9065
  servlet:
    context-path: /example-users

spring:
  application:
    name: example-users
  data:
    mongodb:
      database: example-users
security:
  oauth2:
    client:
      client-id: example-users
      client-secret: example